### ISSUE TITLE
check skipped due to errors

### ISSUE THREAD

**Issue by thiagoalmeidasa** [tfsec/tfsec#518] opened 2020-11-17 14:40 UTC
**Describe the bug**
[This resource](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/examples/complete/main.tf#L79) causes the error `WARNING: skipped AWS017 check due to error(s): value is null`

And it happens even if I try to explicit skip `AWS017` from cli:

```
tfsec --exclude AWS017
WARNING: skipped AWS017 check due to error(s): value is null
```

tfsec version:
```
tfsec --version
v0.36.6
```

**Comment by anhdle14** [comment] 2020-12-09 04:11
Also AWS017 doesn't work as intended.

```bash

Problem 1

  [AWS017][ERROR] Resource 'aws_s3_bucket.this' defines an unencrypted S3 bucket (missing server_side_encryption_configuration block).

       5 |   enable_key_rotation = true
       6 | }
       7 | 
       8 | resource "aws_s3_bucket" "this" {
       9 |   bucket = "accesslog"
      10 |   acl    = "private"
      11 | 
      12 |   lifecycle_rule {
      13 |     id      = "log"
      14 |     enabled = true
      15 | 
      16 |     prefix = "log/"
      17 | 
      18 |     tags = {
      19 |       "rule"      = "log"
      20 |       "autoclean" = "true"
      21 |     }
      22 | 
      23 |     transition {
      24 |       days          = 30
      25 |       storage_class = "STANDARD_IA" # or "ONEZONE_IA"
      26 |     }
      27 | 
      28 |     transition {
      29 |       days          = 60
      30 |       storage_class = "GLACIER"
      31 |     }
      32 | 
      33 |     expiration {
      34 |       days = 90
      35 |     }
      36 | 
      37 |     server_side_encryption_configuration {
      38 |       rule {
      39 |         apply_server_side_encryption_by_default {
      40 |           kms_master_key_id = aws_kms_key.s3.arn
      41 |           sse_algorithm     = "aws:kms"
      42 |         }
      43 |       }
      44 |     }
      45 | 
      46 |     versioning {
      47 |       mfa_delete = true
      48 |     }
      49 | 
      50 |     #checkov:skip=CKV_AWS_18:This S3 does not need logging to be enabled
      51 |     #tfsec:ignore:AWS002 This S3 does not need logging to be enabled
      52 |   }
      53 | }

   See https://tfsec.dev/docs/aws/AWS017/ for more information. 

  disk i/o             2.366412ms
  parsing HCL          22.782µs
  evaluating values    180.055µs
  running checks       518.931µs
  files loaded         5

1 potential problems detected.
```

**Comment by owenrumney** [comment] 2021-02-13 13:46
@thiagoalmeidasa  The problem with the module reference is that it is the module definition rather than an actual `aws_s3_bucket` resources. AWS017 is looking for a `block` in a `resource` called `aws_s3_bucket`. What is in that module is an `attribute` that is being passed into the module as a dynamic variable.

@anhdle14  - I've built a test for this example, its failing because the `lifecyle_rule` block is missing a closing brace

**Closed** 2021-02-13 19:01 UTC
Labels: Waiting for input, bug, good first issue
