### ISSUE TITLE
AWS053: Reporting Error although Key was specified.

### ISSUE THREAD

**Issue by gluehbirnenkopf** [tfsec/tfsec#506] opened 2020-11-11 08:51 UTC
Rule AWS053 was tested with the following RDS Instance code (excerpt):

```hcl
resource "aws_db_instance" "mysql" {
....
  deletion_protection             = var.deletion_protection
  performance_insights_enabled    = var.performance_insights_enabled
  performance_insights_kms_key_id = var.kms_key_arn
  skip_final_snapshot             = var.skip_final_snapshot
  kms_key_id                      = var.kms_key_arn
...
````

Rule 53 is showing an error although a `performance_insights_kms_key_id` is specified.
Looking at the rule, it checks that the `performance_insights_kms_key_id` is not empty. Which should be fine.

Regards,
GK

**Comment by owenrumney** [comment] 2020-11-24 21:46
Duplicate of #505

**Comment by owenrumney** [comment] 2020-11-24 21:54
Maybe not entirely a duplicate - @gluehbirnenkopf can you clarify what you have for your defaults in the variables or if you're using tfvars file?

if I test with the snippet below - I get the error as expected

```terraform
variable "kms_key_arn" {
	default = ""
}

variable "performance_insights_enabled" {
	type = bool
	default = true
}

resource "aws_db_instance" "foo" {
  name                 = "bar"
  deletion_protection             = var.deletion_protection
  performance_insights_enabled    = var.performance_insights_enabled
  performance_insights_kms_key_id = var.kms_key_arn
  skip_final_snapshot             = var.skip_final_snapshot
  kms_key_id                      = var.kms_key_arn
}
```

**Comment by CalvinRodo** [comment] 2020-12-09 15:51
I'm running into this same issue you can see it here: https://github.com/cds-snc/covid-alert-server-staging-terraform/pull/59

**Comment by owenrumney** [comment] 2020-12-09 16:41
Hey @CalvinRodo  - I took a look at your example. Seems like maybe you have a typo in the ARN so its not resolving as valid entry?

I *think* that you need to be using `data.aws_caller_identity.current.account_id` rather than `aws_caller_identify,current.account_id`

Can you give that a go and see if it resolves it?

**Comment by CalvinRodo** [comment] 2020-12-09 16:53
Thanks for checking this out, I caught this issue as soon as you commented. 

Just ran it again and removed the ignore. 

Ran into the same issue: https://github.com/cds-snc/covid-alert-server-staging-terraform/pull/59#issuecomment-741897750

**Comment by CalvinRodo** [comment] 2020-12-09 16:55
Double checking again because now tf validate is failing. I'll update with results.

**Comment by owenrumney** [comment] 2020-12-09 16:57
I think there is still potentially an issue that it should be
`data.aws_caller_identity.current.account_id`

tfsec will parse the whole context and build it up - I think what is
happening here is that the hcl expression in that template can't be parsed
because there is nothing in the hcl context at the moment.

It looks from the action that it is getting a `terraform init` so it would
be there.

I think a terraform plan of it now would most likely show that there is a
problem?

**Comment by owenrumney** [comment] 2020-12-09 17:12
whats interesting is that I just pulled down the PR to test locally and it only loads 28 files. 

If you don't mind I'll use your PR to dig into this a bit

**Comment by CalvinRodo** [comment] 2020-12-09 17:17
No worries, it's open source. 

Running a plan now it takes a while so I'll report back

**Comment by CalvinRodo** [comment] 2020-12-09 17:24
So running a plan I get the following output on that specific resource: 

```hcl
  # aws_rds_cluster_instance.covidshield_server_instances[2] will be updated in-place
  ~ resource  aws_rds_cluster_instance.covidshield_server_instances[2] {
        arn                             = "arn:aws:rds:ca-central-1:005133826942:db:server-instance-2"
        auto_minor_version_upgrade      = true
        availability_zone               = "ca-central-1d"
        ca_cert_identifier              = "rds-ca-2019"
        cluster_identifier              = "server-cluster"
        copy_tags_to_snapshot           = false
        db_parameter_group_name         = "default.aurora5.6"
        db_subnet_group_name            = "server"
        dbi_resource_id                 = "db-JHCOGGU6ZRWMP5QY7LUYR34RFA"
        endpoint                        = "server-instance-2.ciev9ck1x9wj.ca-central-1.rds.amazonaws.com"
        engine                          = "aurora"
        engine_version                  = "5.6.mysql_aurora.1.22.2"
        id                              = "server-instance-2"
        identifier                      = "server-instance-2"
        instance_class                  = "db.t3.small"
        kms_key_id                      = "arn:aws:kms:ca-central-1:005133826942:key/33b5e530-a36c-4601-aa30-830f5c2f243d"
        monitoring_interval             = 0
        performance_insights_enabled    = true
      ~ performance_insights_kms_key_id = "arn:aws:kms:ca-central-1:005133826942:key/33b5e530-a36c-4601-aa30-830f5c2f243d" -> "arn:aws:kms:ca-central-1:005133826942:alias/aws/rds"
        port                            = 3306
        preferred_backup_window         = "07:00-09:00"
        preferred_maintenance_window    = "mon:06:44-mon:07:14"
        promotion_tier                  = 0
        publicly_accessible             = false
        storage_encrypted               = true
        tags                            = {
            "CostCentre" = "CovidShield"
            "Name"       = "server-instance"
        }
        writer                          = false
    }
```

so it is picking up the new resource. 

However I'm pretty safe to ignore this rule specifically because we already are encrypting using the managed key. 

Feel free to continue to dig into it but I'm going to specifically remove that attribute and ignore the rule since it's not valid for this specific case. 

Let me know if you have any questions would be happy to help in anyway I can.

**Comment by owenrumney** [comment] 2020-12-09 20:07
@CalvinRodo  - the issue with your case seems to be the resolution of the `data.aws_caller_identity.current` and the hcl libraries not "getting" terraform objects, it doesn't know that there is an attribute called `account_id` on that.

The PR I've raised will mitigate that sort of thing when things are being concatenated up in that way.

@gluehbirnenkopf  - yours is a bit different, I believe it's just that at scan time there are no resolvable values for `var.kms_key_arn`; I'm guessing because you don't have a default value which makes sense.

You can resolve this by having a tfsecvars file that you use when running and pass it `--tfvars-file tfsecvars`

**Comment by CalvinRodo** [comment] 2020-12-09 20:09
@owenrumney Thanks for checking in on this, when I was looking at the code for your project I had a feeling that's what was happening.

**Closed** 2020-12-09 20:12 UTC
Labels: aws, bug, good first issue
