### ISSUE TITLE
Latest release increased scanning time from a few seconds to 6+ minutes

### ISSUE THREAD

**Issue by favoretti** [tfsec/tfsec#625] opened 2021-02-24 08:33 UTC
Latest releases increased scanning time from a few seconds to 6+ minutes.
I've seen some talks about reducing looping on nested modules, which seems to have helped a bit, but scanning time is still exceptionally high.

**Comment by yhekma** [comment] 2021-02-24 16:47
could this have something to do with
https://github.com/tfsec/tfsec/blob/master/internal/app/tfsec/parser/evaluator.go#L93
?

If I follow the logic correctly (which given the fact I am unfamiliar with this codebase as of yesterday is a big if) this is adding blocks of "submodules" to be evaluated *in addition* of the modules themselves no? Attaching a debugger, I see the evaluator at one time has ~450 blocks in one of our codebases, while if I try the same with the 0.37.3 tag, at most it's 10. Now of course I could just remove the line (which I did of course to see what would break) and it *seems* it solves this issue. I am just not 100% clear its safe to do so. Am I missing a testsuite?

**Comment by owenrumney** [comment] 2021-02-24 20:59
Hey @yhekma  - this is an ongoing headache trying to solve the issue of modules with nested modules. Examples like the google terraform modules use a lot of sub modules and sub sub modules that need to be resolved to complete the full picture before the scanning begins. 

While only resources in modules that are used are actually checked against, we do end up evaluating all the resources in the nested modules upfront.

Do either of you have public repo structures where this is causing an issue we could see the issue in action?

**Comment by owenrumney** [comment] 2021-02-24 21:01
Looking at that code you've highlighted in the evaluator I'm wondering if a merging approach might actually be a good option here  - its feasible there are significant dupes in there depending on the module structure

**Comment by favoretti** [comment] 2021-02-25 07:42
@owenrumney unfortunately we can't open that code up without exposing way too much, but I'd be happy to facilitate a screen share, online debugging or anything that would help you tackle this.

**Comment by owenrumney** [comment] 2021-02-25 08:26
Hey @favoretti - that's cool, and I expected that answer but worth asking just in case. 

Are you able to take the v0.39.1 pre-release binary (still building is I type this) and try. I've made a fairly minor tweak that I'm hoping will resolve this

**Comment by yhekma** [comment] 2021-02-25 09:27
Hi @owenrumney - I just tested it with the v0.39.1 tagged code and see the following

## v0.39.1
```
  disk i/o             13.222975218s
  parsing HCL          106.15151ms
  evaluating values    1m39.383273445s
  running checks       14.683313ms
  files loaded         250

1 potential problems detected.
```
The problem stated was in a sub sub module

## v0.37.3
```
  disk i/o             2.203314444s
  parsing HCL          17.338519ms
  evaluating values    2.706314992s
  running checks       7.44759ms
  files loaded         250

No problems detected!
```

## v0.38.6
```
  disk i/o             16.567785883s
  parsing HCL          134.753215ms
  evaluating values    6m28.267749894s
  running checks       11.9022ms
  files loaded         250

1 potential problems detected.
```
Same sub sub module as in 0.39.0

So thats already a *huge* improvement.
 Like @favoretti stated, although we cannot open up the code in question, let me know if I can do anything to help out. I'll look into setting up a small test today to isolate this and make it easier to work and test on it. Just something to reproduce this particular issue

**Comment by favoretti** [comment] 2021-02-25 10:37
1m40 is indeed quite an improvement! Thanks for that.

**Comment by owenrumney** [comment] 2021-02-25 11:31
Hey @favoretti  and @yhekma  - We've got a prerelease version v0.39.3 - would you mind running that through. It's not likely to be a whole lot quicker but the output will show us the volumes we're looking for.

Thanks for your help debugging this

**Comment by favoretti** [comment] 2021-02-25 12:24
150 seconds for a run from the master. Do you want a debug log?

**Comment by owenrumney** [comment] 2021-02-25 12:36
Yes please - and the statistics at the end please. it'll show us how many resources and modules are being processed

**Comment by yhekma** [comment] 2021-02-25 12:55
Even better. Debug log with stats at the end attached.

Output of `go run cmd/tfsec/main.go /Users/yhekma/Dev/TNT/fdx-strat-pgm/atlas-terraform/prod --verbose | gzip -c >  log` when commit `3f4139a` is checked out. 
[log.gz](https://github.com/tfsec/tfsec/files/6043032/log.gz)

**Comment by owenrumney** [comment] 2021-02-25 13:15
hmmm

132k blocks being processed in 47s is pretty good. v0.37.1 wasn't loading in modules correctly, so I think this leap in runtime is due to everything actually being processed correctly now.

In the debug log, I see a lot of the module `adf_secondary.kv.labels` being loaded. we found that if you don't load that for each usage you don't check the specifics of that usage properly. 

lines 70216 - 70244 highlights this nicely, you can see the module being requested in `diagnostics.tf`, `penp.tf`, `labels.tf` and again in `labels.tf` but for a different module. 

I think we can say this is working as designed

**Comment by yhekma** [comment] 2021-02-25 13:35
Yeah I agree. Thanks for the swift reply (and fix)!

**Comment by favoretti** [comment] 2021-02-25 13:37
If you would be so kind to release this, we can rebuild our agents to use the latest and actually save us from suffering! :) Thanks!

**Comment by owenrumney** [comment] 2021-02-25 13:56
Yup - released as https://github.com/tfsec/tfsec/releases/tag/v0.39.3 - thanks for using tfsec ;-)

**Comment by favoretti** [comment] 2021-02-26 08:36
BTW, beating a dead horse here, but an old colleague of mine wrote https://katydid.github.io/ - it's probably an overkill, but _might_ help gain speed on large codebases?

**Comment by owenrumney** [comment] 2021-02-26 08:40
Thanks, @favoretti  - one of the things that I think stand tfsec apart from some of the others is that it parses the HCL and builds the whole model so that it is accurately resolving variables etc. To do that we defer the parsing of the HCL to the hashicorp parser then we deal with the output. 

The majority of the `evaluating values` time is actually spent in the hashicorp library. To pull that out and parse our own I think would be a monumental task :thinking: 

I Will take a look anyway, seems like a cool library :+1:

**Comment by owenrumney** [comment] 2021-02-26 08:40
Are we good to close this ticket now?

**Comment by favoretti** [comment] 2021-02-26 08:45
Thank you for explaining. Yeah, I think so, we're in a much better shape now! 
Thanks again for the quick turnaround.

**Closed** 2021-02-26 08:47 UTC
Labels: investigating
